name: Mod-Request
main: com.grumpybear.modreq.modreq
version: 1.0
author: GrumpyBear57
description: Modreq plugin, similiar to an IRL ticketing system.
commands: 
  modreq: 
    description: Submit a request to the staff. 
    usage: /modreq [Request]
  modqueue: 
    description: Allows staff to see open tickets.
    usage: /modqueue
  reqaccept: 
    description: Allows staff to assign a ticket to themself.
    usage: /reqaccept [Ticket ID] 
  reqresovle: 
    description: Allows staff or submitter to close a ticket after they've resolved it.
    usage: /reqresolve <Note to user>
  reqclose: 
    description: Allows staff to close a ticket without resolution. Usefull for troll tickets.
    usage: /reqclose <Note to user> 
  reqabandon:
    description: Allows staff to resign from a ticket, putting it back in the queue.
    usage: /reqabandon
  reqesc: 
    description: Allows mods to escalate a ticket to admins.
    usage: /reqesc [Note to admin]
  reqtp: 
    description: Allows staff to teleport to the location the ticket was place at.
    usage: /reqtp [Ticket ID]
  reqnote: 
    description: Allows staff or submitter to add a note to a ticket, usefull for extra information that may be required.
    usage: /reqnote [Note]
  reqstatus: 
    description: Allows staff or submitter to see the status of a ticket.
    usage: /reqstatus [Ticket ID]
  modstats: 
    description: Shows some modreq information about a user.
    usage: /modstats <user> 
  modmode: 
    description: Toggles a variety of mod tool with one command. 
    usage:  /modmode 