name: Mod-Request
main: com.grumpybear.modreq.main
version: 1.0.0
author: GrumpyBear57
description: Modreq plugin, similiar to an IRL ticketing system.
commands: 
  modreq: 
    description: Submit a request to the staff. 
    usage: /modreq [Request]